tosca_definitions_version: tosca_simple_yaml_1_3

imports:

- nodes.yaml

group_types:

  Namespace:
    description: >-
      Will automatically use a "group" label (the name of the group) for all deployment controllers.
    members:
    - Service
    properties:
      namespace:
        type: string
